export { default as ShopDashboard } from './pages/Dashboard';
export { default as ShopRegistrationPage } from './pages/ShopRegistrationPage';
export { default as CustomersPage } from './pages/customers/CustomersPage';
export { default as ShopNotificationsPage } from './pages/notifications/ShopNotificationsPage';
export { default as ShopProfilePage } from './pages/profile/ShopProfilePage';
export { default as ShopReportsPage } from './pages/reports/ShopReportsPage';
export { default as ShopReviewsPage } from './pages/reviews/ShopReviewsPage';
export { default as WhatsAppQRPage } from './pages/whatsapp/WhatsAppQRPage';
export { default as ShopWhatsAppPage } from './pages/whatsapp-manage/ShopWhatsAppPage';
